name: C/C++ CI

on: [ push , pull_request ]

 
jobs:

  static_analyse:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run Cppcheck
      uses: Bedzior/cppcheck-action@main
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
    #- name: cppcheck
      #uses:  deep5050/cppcheck-action@main
      #with:
        #github_token: ${{ secrets.GITHUB_TOKEN}}
        
    #- name: publish report    
      #uses: mikeal/publish-to-github-action@master
      #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #BRANCH_NAME: 'static_analysis' #branch name goes here
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: IQuizt cppcheck Errorlist
        path: cppcheck_report.txt        
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: chmod
      run: chmod +x ubuntu_build.sh
    - name: ubuntu
      run: ./ubuntu_build.sh
    - name: Send custom variable to Meercode Build
      uses: meercodeio/meercode-custom-variable@0.1.0
      with:
        meercode-token: ${{secrets.MEERCODE_TOKEN}}
        url: 'https://github.com/CMDR14/IQuizt'
    
    
  test-persistence:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: create build folder, build test and run it
      run : |
        cd ..
        mkdir build_test
        cd build_test
        cmake ../IQuizt
        make PersistenceTest
        cd ./tests/PersistenceTest/
        ctest
        
  test-quizitemeditor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: create build folder, build test and run it
      run : |
        cd ..
        mkdir build_test
        cd build_test
        cmake ../IQuizt
        make QuizItemEditorTest
#        cd ./tests/quizitemedtiortest/
#        ctest
#        Couldn't test because it needs a display. 
 
  test-quizitem:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: create build folder, build test and run it
      run : |
        cd ..
        mkdir build_test
        cd build_test
        cmake ../IQuizt
        make QuizItemTest
        cd ./tests/QuizItemTest/
        ctest
        
        
