name: C/C++ CI

on: [ push , pull_request ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update -yqq
    - name: essential
      run: sudo apt-get install -yqq build-essential cmake
    - name: qt
      run: sudo apt-get install -yqq qt5-default
    - name: chmod
      run: chmod +x ubuntu_build.sh
    - name: ubuntu
      run: ./ubuntu_build.sh
    - name: Send custom variable to Meercode Build
      uses: meercodeio/meercode-custom-variable@0.1.0
      with:
        meercode-token: 'MmDV0sjlXKTtZOO2UoYAwA3B7VlUTYRQ'
        url: 'https://github.com/CMDR14/IQuizt'
    
    
  test-persistence:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update -yqq
    - name: essential
      run: sudo apt-get install -yqq build-essential cmake
    - name: qt
      run: sudo apt-get install -yqq qt5-default
    - name: create build folder and build test
      run : |
        cd ..
        mkdir build_test
        cd build_test
        cmake ../IQuizt
        make PersistenceTest
    - name : run test
      run : |
        chmod +x tests/PersistenceTest/PersistenceTest
        ./tests/PersistenceTest/PersistenceTest
        
  test-quizitemeditor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update -yqq
    - name: essential
      run: sudo apt-get install -yqq build-essential cmake
    - name: qt
      run: sudo apt-get install -yqq qt5-default
    - name: create build folder
      run : |
        cd ..
        mkdir build_test
        cd build_test
    - name : Create MAKEFILE
      run : cmake ../IQuizt/tests
    - name : build QuizItemEditor test
      run : make QuizItemEditorTest
    - name : run test
      run : |
        chmod +x quizitemedtiortest/QuizItemEditorTest
        ./quizitemedtiortest/QuizItemEditorTest
    
  test-quizitem:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update -yqq
    - name: essential
      run: sudo apt-get install -yqq build-essential cmake
    - name: qt
      run: sudo apt-get install -yqq qt5-default
    - name: create build folder
      run : |
        cd ..
        mkdir build_test
        cd build_test
    - name : Create MAKEFILE
      run : cmake ../IQuizt
    - name : build QuizItem test
      run : make QuizItemTest
    - name : run test
      run : |
        chmod +x tests/QuizItemTest/QuizItemTest
        ./tests/QuizItemTest/QuizItemTest
        
        
