name: C/C++ CI

on: [ push , pull_request ]
    

jobs:
  build:
    needs: [test-persistence,test-quizitemeditor,test-quizitem]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default
    - name: chmod
      run: chmod +x ubuntu_build.sh
    - name: ubuntu
      run: ./ubuntu_build.sh
    - name: Send custom variable to Meercode Build
      uses: meercodeio/meercode-custom-variable@0.1.0
      with:
        meercode-token: ${{secrets.MEERCODE_TOKEN}}
        url: 'https://github.com/CMDR14/IQuizt'
    
    
  test-persistence:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default
    - name: create build folder, build test and run it
      run : |
        cd ..
        mkdir build_test
        cd build_test
        cmake ../IQuizt
        make PersistenceTest
        cd ./tests/PersistenceTest/
        ctest
        
  test-quizitemeditor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default
    - name: create build folder, build test and run it
      run : |
        cd ..
        mkdir build_test
        cd build_test
        cmake ../IQuizt
        make QuizItemEditorTest
#        cd ./tests/quizitemedtiortest/
#        ctest
#        Couldn't test because it needs a display. 
 
  test-quizitem:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default
    - name: create build folder, build test and run it
      run : |
        cd ..
        mkdir build_test
        cd build_test
        cmake ../IQuizt
        make QuizItemTest
        cd ./tests/QuizItemTest/
        ctest

  create-documentation:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
    - name: Generate with Doxygen
      run: doxygen Doxyfile
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: IQuizt Documentation
        path: docs/*
        
        
