name: Default CI Workflow

on: 
  push:
    branches-ignore:
      - release
 
jobs:  
        
  build:
    needs: [test-persistence,test-quizitemeditor,test-quizitem]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: chmod
      run: chmod +x ubuntu_build.sh
    - name: ubuntu
      run: ./ubuntu_build.sh
    - name: Send custom variable to Meercode Build
      uses: meercodeio/meercode-custom-variable@0.1.0
      with:
        meercode-token: ${{secrets.MEERCODE_TOKEN}}
        url: 'https://github.com/CMDR14/IQuizt'
    - name: Install binary
      run: |
        cd ../build
        make install
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: IQuizt Executable
        path: Release
    
  test-persistence:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: build test and run it
      run : bash ./test_build.sh PersistenceTest -ctest
        
  test-quizitemeditor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: build test and run it
      run : bash ./test_build.sh quizitemedtiortest
 
  test-quizitem:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt5-default cppcheck
    - name: build test and run it
      run : bash ./test_build.sh QuizItemTest -ctest

  create-documentation:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
    - name: Generate with Doxygen
      run: doxygen Doxyfile
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: IQuizt Documentation
        path: docs/*

  cppcheck:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cppcheck
      uses:  deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        enable: all
        other_options: --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=preprocessorErrorDirective --suppress=unmatchedSuppression:* --suppress=missingInclude
    - name: show_report
      run: bash ./cppcheck_action_result.sh cppcheck_report.txt
        
        
