name: C/C++ CI

on: [ push , pull_request ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: apt-get update -yqq
    - name: essential
      run: apt-get install -yqq build-essential cmake
    - name: qt
      run: apt-get install -yqq qt5-default
    - name: ubuntu
      run: ./ubuntu_build.sh
